#[path = "lib/bash.rs"]
pub mod bash;
#[path = "lib/config.rs"]
pub mod config;
#[path = "lib/ssh.rs"]
pub mod ssh;
#[path = "lib/python.rs"]
pub mod python;
#[path = "lib/rand.rs"]
pub mod rand;
#[path = "lib/venv.rs"]
pub mod venv;
#[path = "lib/ai.rs"]
pub mod ai;
